//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2GIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBObjChanges
    {
        public int ID { get; set; }
        public System.DateTime DBObjChangeDate { get; set; }
        public string DBObjChangeType { get; set; }
        public string DBObjChange { get; set; }
        public string DBObjChangeXML { get; set; }
        public string DBObjType { get; set; }
        public string DatabaseName { get; set; }
        public string SchemaName { get; set; }
        public string ObjectName { get; set; }
        public string HostName { get; set; }
        public string Program { get; set; }
        public string LoginUser { get; set; }
        public string IPAddress { get; set; }
        public string ChangeComment { get; set; }
        public Nullable<System.Guid> BatchID { get; set; }
        public Nullable<System.DateTime> WritingToGIT { get; set; }
        public string GitLink { get; set; }
    }
}
